Style/FrozenStringLiteralComment:
  Enabled: false
  
Style/ClassVars:
  Enabled: false

Style/GuardClause:
  Enabled: false
  
Style/Documentation:
  Enabled: false
  
Metrics/LineLength:
  Max: 165
  
Lint/UselessAssignment: 
  Enabled: false

